selftests: kselftest_harness: Print emptry string, not empty fmt on PASS/FAIL
When printing nothing for the diagnostic on PASS/FAIL, use a string format
with an empty string, not an empty format with a NULL parameter.  Clang
complains about the empty format string, which in turn breaks building
with -Werror.

../kselftest_harness.h:1205:30: error: format string is empty [-Werror,-Wformat-zero-length]
                              diagnostic ? "%s" : "", diagnostic);
                                                  ^~
Fixes: 378193eff339 ("selftests: kselftest_harness: let PASS / FAIL provide diagnostic")
Cc: Kees Cook <keescook@chromium.org>
Cc: Jakub Kicinski <kuba@kernel.org>
Signed-off-by: Sean Christopherson <seanjc@google.com>